name: audiometer_source
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
    
    
  shared_preferences: ^2.5.2
  path: ^1.9.1
  sqflite: ^2.4.2
  audioplayers: ^6.1.2
  syncfusion_flutter_charts: ^28.2.5+1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/audio/0/
    - assets/audio/1/
    - assets/audio/2/
    - assets/audio/3/
    - assets/audio/4/



